- name: copy config haproxy
  when: haproxy_config_template is defined
  template:
    src: "{{ haproxy_config_template }}"
    dest: "{{ haproxy_config_file_path }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
    validate: haproxy -c -V -f %s
  notify: reload haproxy
