- name: install nvm
  become: yes
  shell: "{{ wb_nodejs_install_cmd }}"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: install node and set version
  become: yes
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ nodejs_version }} && nvm alias default {{ nodejs_version }}"
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/alias"
